### ISSUE TITLE
Support opting into a pickup

### ISSUE THREAD

**Issue by sdwilsh** [bachya/aioridwell#17]
**Is your feature request related to a problem? Please describe.**
It would be great to be able to programmatically opt in to a pickup with this API (which I don't think is possible based on the docs, but if it is, the docs might need a more clear example).

**Describe the solution you'd like**
I don't think I'm have a strong opinion on how this would be implemented.

**Additional context**
Overall goal would be for me to be able to have a few Home Assistant automations that work with Todoist to be able to opt me in without going their site.

**Comment by bachya** [comment]
This should be doable:

1. Adding a generic "opt into X pickup with Y pickup types" should be pretty straightforward.
2. How will this translate to Home Assistant? A service to simply opt into the next pickup (with the assumption that you will go to their website to update types/quantities afterward) is straightforward; attempting to update all that from Home Assistant itself will require some thought on a clear UX.

I'll get started on 1; what are your thoughts on 2?

**Comment by sdwilsh** [comment]
For me at least, most of the time I have something in the default categories and nothing else, so just opting into the default without adjusting any quantities is fine.  When I do have one of the special categories, I'm honestly okay with just going to the website.

The big automation I want is to a) opt me in, b) add a todo in todoist to but the bags in the bin the night before (I forgot to do this important step more than I'd like to admin), and probably c) add a todo to check the special category.  I pretty much always have at least plastic to pick up, so the only time I'd not opt into a pickup is if I were away from home, and I can automate that check too.

While I'm writing this, I realize that Ridwell used to have us opt-in to any category we wanted for pickup in Seattle, but they started to not ask for that in the core areas.  As they expand, I don't know how they handle it in a given market, so maybe more thought does need to be put into (2) and (3) than I'm doing.

**Comment by bachya** [comment]
Got it. Let's start with simple opt-in/opt-out and we'll go from there.

**Comment by bachya** [comment]
@sdwilsh This is now merged into the API. I'll cut a release and put together a Home Assistant PR soon; I'll post back here when I do.

**Comment by sdwilsh** [comment]
Great!  I've got some friends interested in this as well!

**Comment by bachya** [comment]
@sdwilsh FYI: https://github.com/home-assistant/core/pull/62293. I've tested and it works great. 👍🏻 Note that because HA will skip a January release, the earliest this will land is in 2022.2.0. If you want, you can always download that PR's files into a [custom component](https://developers.home-assistant.io/docs/creating_integration_file_structure/#where-home-assistant-looks-for-integrations).
